### ISSUE TITLE
Update README with links to wiki page & mailing list

### ISSUE THREAD

**Issue by hdamker** [camaraproject/CustomerInsights#4]
**Expected action**

- [x] wiki page for CustomerInsights created
- [x] mailing list sp-customerinsights created
- [x] respective links in README updated

**Comment by hdamker** [comment]
@camaraproject/admins @eharrison24 @wrathwolf Would you take this?

**Comment by wrathwolf** [comment]
I've created the wiki page, added the mailing list, and opened a PR to update the README.md.
