### ISSUE TITLE
Meetings Schedule

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/CustomerInsights#8]
**Problem description**
It is needed to agree on a timeslot to have our regular meetings (bi-weekly based in principle).

**Expected action**
Agree on Meeting Schedule for Customer Insights. 

**Additional context**
Below it is proposed some slots to agree on one of them

**Comment by PedroDiez** [comment]
Proposed time slots (I can in all of them): 
@amg77, @rartych, @KevScarr, please let me know your preferences

Tuesday:
- 14:30 - 15:30 UTC
- 15:30 - 16:30 UTC

Wednesday:
- 09:00 - 10:00 UTC
- 10:00 - 11:00 UTC
- 15:00 - 16:00 UTC

Thursday:
- 14:00 - 15:00 UTC
- 15:00 - 16:00 UTC 

Friday:
- 10:00 - 11:00 UTC
- 11:00 - 12:00 UTC

**Comment by KevScarr** [comment]
@PedroDiez My availability included below, from late November onwards...

Tuesday:
14:30 - 15:30 UTC [yes]
15:30 - 16:30 UTC [yes]

Wednesday:
09:00 - 10:00 UTC [yes]
10:00 - 11:00 UTC [no]
15:00 - 16:00 UTC [yes]

Thursday:
14:00 - 15:00 UTC [yes]
15:00 - 16:00 UTC [yes]

Friday:

10:00 - 11:00 UTC [no]
11:00 - 12:00 UTC [no]

**Comment by rartych** [comment]
Here is my availability:

(week numbers as in Outlook calendar)

Tuesday:

  *   14:30 - 15:30 UTC – no – only 14:30-15:00
  *   15:30 - 16:30 UTC - no

Wednesday:

  *   09:00 - 10:00 UTC – no
  *   10:00 - 11:00 UTC – yes
  *   15:00 - 16:00 UTC -  yes – biweekly (even week numbers only, not to collide with  Camara ICM)

Thursday:

  *   14:00 - 15:00 UTC – yes
  *   15:00 - 16:00 UTC – yes – collision with CAMARA All Hands call once a month

Friday:

  *   10:00 - 11:00 UTC – yes – biweekly (even week numbers only)
  *   11:00 - 12:00 UTC – yes
Regards,
Rafal



T-MOBILE POLSKA S.A. z siedzibą w Warszawie
Adres: ul. Marynarska 12, 02-674 Warszawa
Zarząd Spółki:
Andreas Maierhofer - Prezes Zarządu;
Juraj Andráš - Członek Zarządu, Dyrektor ds. Finansowych;
Dorota Kuprianowicz-Legutko – Członkini Zarządu, Dyrektorka ds. HR, Prawnych i Bezpieczeństwa;
Goran Marković – Członek Zarządu, Dyrektor ds. Rynku Prywatnego;
Alexander Jenbar – Członek Zarządu, Dyrektor ds. Technologii i Innowacji;
Agnieszka Rynkowska - Członek Zarządu, Dyrektor ds. Rynku Biznesowego.
Spółka zarejestrowana w Sądzie Rejonowym dla m.st. Warszawy w Warszawie,
XIII Wydział Gospodarczy Krajowego Rejestru Sądowego.
KRS 0000391193 | NIP 526-10-40-567 | Regon 011417295
Kapitał zakładowy 711.210.000 złotych, kapitał wpłacony w całości.

DUŻE ZMIANY ZACZYNAJĄ SIĘ OD MAŁYCH - CHROŃ PLANETĘ, NIE DRUKUJ TEGO E-MAILA, JEŻELI NIE MUSISZ.

Ta wiadomość i jej treść są zastrzeżone w szczegółowym zakresie dostępnym na http://www.t-mobile.pl/stopka
This e-mail and its contents are subject to a DISCLAIMER with important RESERVATIONS: see http://www.t-mobile.pl/stopka

**Comment by PedroDiez** [comment]
Thanks @KevScarr , @rartych for your input.
cc @amg77 

Let's do then:

Thursday:
14:00 - 15:00 UTC

First meeting would be on 28th November (let me confirm once I have managed with Linux Foundation)

**Comment by PedroDiez** [comment]
Sent link via Teams, until we have zoom option available

**Comment by KevScarr** [comment]
@PedroDiez Are you able to share the meeting link here or point me in the direction of where to find it please?

**Comment by PedroDiez** [comment]
@KevScarr, @rartych @amg77 Temporal Meeting Link. I have to manage Zoom meetings yet

[Join Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTI4NWRmNjMtNGRjYy00OWZiLTg5OWYtMzU4ODBlYTc4ZmFl%40thread.v2/0?context=%7b%22Tid%22%3a%229744600e-3e04-492e-baa1-25ec245c6f10%22%2c%22Oid%22%3a%2219764050-b5d5-4991-9f15-d10905a94c08%22%7d) 
Meeting Id: 374 225 966 936 
Access Code: gw2Wj3zU

**Comment by PedroDiez** [comment]
Already have Zoom Meeting: 
https://zoom-lfx.platform.linuxfoundation.org/meeting/95737002367?password=034d9b74-a944-4def-ae30-0f93802430a5

Have contacted LF to adapt to 14:00 - 15:00 UTC.

Let's use tomorrow this link
@KevScarr, @rartych @amg77
